### ISSUE TITLE
support long quotes

### ISSUE THREAD

**Issue by boferri** [knutwalker/NtParser#1]
albeit, it's not part of the ntriples spec (grammar), it might be good to support long quotes for literals as they are part of the turtle spec (see http://www.w3.org/TR/turtle/#grammar-production-STRING_LITERAL_LONG_QUOTE).

note: long quotes are like CDATA for XML Elements ;)

**Comment by knutwalker** [comment]
Since long quotes aren't part of the N-Triples spec, the [official test suite](http://www.w3.org/2013/N-TriplesTests/) [checks](http://www.w3.org/2013/N-TriplesTests/nt-syntax-bad-string-05.nt), that parsing long quotes will fail. So, only the `NonStrictNtParser` will support this.

It's available in version 0.2 which is in maven central in a couple of hours.

**Comment by boferri** [comment]
thx!!!

**Comment by boferri** [comment]
ok, got it right now. long quotes or long literals (that's how the called in the turtle spec, see http://www.w3.org/TeamSubmission/turtle/#sec-tutorial) are simply to allow line breaks lin literals (which makes sense for Turtle, but not for N-Triples, since each line is a triple or statement there). so it looks like that there is no equivalent to CDATA in Turtle etc. hence, anything else needs to be escaped in a literal string.

**Comment by knutwalker** [comment]
Ok, I suppose that make senses. If you have a literal without line breaks but many quotes, it may be convenient to use the long quotes (btw, called triple quotes in Scala and Python) anyway (and we can parse the GND dump now (: ).
